### PR TITLE
Fix Windows path separator bug

### LINKED ISSUE #81: Compiler error on Windows when using directories due to slash
As initially reported in https://github.com/dillonkearns/elm-pages-starter/issues/1, I'd like to open the issue against this repo, because I assume that the bug is in this code.

To reproduce, try to run `examples/docs` on Windows with `npm start`. You will see the following error message:
```
> elm-pages develop --port 1234

Running elm-pages...
Dependencies ready!
Detected problems in 1 module.
-- PROBLEM IN RECORD ------------------------------------------------- Pages.elm

I am partway through parsing a record, but I got stuck here:

79|     { blog/extensibleMarkdownParsingInElm = (buildPage [ "blog/extensible-markdown-parsing-in-elm" ])
              ^
I just saw a field name, so I was expecting to see an equals sign next. So try
putting an = sign here?

Note: If you are trying to define a record across multiple lines, I recommend
using this format:

    { name = "Alice"
    , age = 42
    , height = 1.75
    }

Notice that each line starts with some indentation. Usually two or four spaces.
This is the stylistic convention in the Elm ecosystem.

(node:8612) UnhandledPromiseRejectionWarning: Compilation failed
(node:8612) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8612) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Dillon [suspected that the bug is in a part of the code splitting on `/` instead of being platform-dependent](https://github.com/dillonkearns/elm-pages-starter/issues/1#issuecomment-534788976).

I would like to provide more detailed information, but I'm not sure how to enable logging or how to debug the code. Any suggestions of how to get more information are welcome.

### PR DESCRIPTION
**Pull request by vViktorPL**
This should fix #81 bug. The problem was that OS path separator was used to split file paths, however as paths are listed through `glob` lib which is platform agnostic in terms of the output scan paths and always separates file paths with `/`: [see details here](https://github.com/isaacs/node-glob#windows).

### CODE REVIEW

File: generator/src/generate-records.js [hunk 1]
```diff
@@ -41,9 +41,9 @@ function unpackFile() {
 function relativeImagePath(imageFilepath) {
   var pathFragments = imageFilepath;
```
Comment (Y0hy0h) [inline generator/src/generate-records.js]: Would it be helpful for future programmers to add a doc comment about the slash issue? E.g.
```
// Because we use node-glob, we must use `/` as a separator on all platforms. See https://github.com/isaacs/node-glob#windows
```

Comment (vViktorPL) [reply generator/src/generate-records.js]: Fixed, please check again :)

Comment (Y0hy0h) [reply generator/src/generate-records.js]: That's a really elegant way of doing it. 👍

**Comment by dillonkearns** [comment]
@all-contributors please add @vViktorPL for code.

**Comment by dillonkearns** [comment]
@all-contributors please add @Y0hy0h for userTesting.

**Comment by dillonkearns** [comment]
@all-contributors please add @Y0hy0h for userTesting.

**Comment by dillonkearns** [comment]
@all-contributors please add @Y0hy0h for userTesting.
